### ISSUE TITLE
Testing and Debugging

### ISSUE THREAD

**Issue by joxyle-jhon** [joxyle-jhon/Stardew-Valley-Mod#9]

**Comment by joxyle-jhon** [comment]
Task: 

- Conduct unit testing for core interactions (dialogues, gifting, heart events).
- Perform integration testing to verify compatibility with the game and SMAPI.
- Test child growth mechanics and resolve any gameplay issues, like child movement bugs.

**Comment by AstirisAQW** [comment]
good job
